using Domain.ValueObjects;

namespace Domain.Entities
{
    public class Donor
    {
        // Primary Key (generated by the database)
        public Guid Id { get; private set; }

        // Donor Info
        public string Name { get; private set; } = string.Empty;
        public string Email { get; private set; } = string.Empty;
        public DateOnly DateOfBirth { get; private set; }
        public BloodType BloodType { get; private set; } = BloodType.APositive();
        public string NIN { get; private set; } = string.Empty; // National ID Number
        public string PhoneNumber { get; private set; } = string.Empty;
        public string Address { get; private set; } = string.Empty;
        public DateOnly LastDonationDate { get; private set; }

        // Navigation Property (One-to-Many with BloodBags)
        public ICollection<BloodBag> BloodBags { get; private set; } = new List<BloodBag>();


        // Optional constructor to create a donor (without setting Id)
        public Donor(
            string name,
            string email,
            DateOnly dateOfBirth,
            BloodType bloodType,
            string nin,
            string phoneNumber,
            string address,
            DateOnly lastDonationDate)
        {
            Name = name;
            Email = email;
            DateOfBirth = dateOfBirth;
            BloodType = bloodType;
            NIN = nin;
            PhoneNumber = phoneNumber;
            Address = address;
            LastDonationDate = lastDonationDate;
        }
        // EF Core requires a parameterless constructor
        private Donor() { }

        public void Update(
    string name,
    string email, 
    DateOnly dateOfBirth,
    BloodType bloodType,
    string nin,
    string phoneNumber,
    string address,
    DateOnly lastDonationDate)
{
    Name = name;
    Email = email;
    DateOfBirth = dateOfBirth;
    BloodType = bloodType;
    NIN = nin;
    PhoneNumber = phoneNumber;
    Address = address;
    LastDonationDate = lastDonationDate;
}
    }
}
