@HSTS_Back_HostAddress = http://localhost:5000

# Test the root route
GET {{HSTS_Back_HostAddress}}/test
Accept: application/json

###

# Test the /test route
GET {{HSTS_Back_HostAddress}}/test
Accept: application/json

###

# Test the /weatherforecast route
GET {{HSTS_Back_HostAddress}}/weatherforecast/
Accept: application/json

###
